name: Lighthouse

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: 'https://www.mini.de/de-de/sl/fahrzeugsuche#/results'
          # Where to output the HTML/JSON reports
          output_path: './lighthouse-report'
          # Any other configs you need...
          # e.g. config_path: './lighthouserc.json'
          # token, server base URL, etc.

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v3
        with:
          # The name the artifact will have in the Actions "Artifacts" section
          name: lighthouse-reports
          # Must point to the same path defined in `output_path`
          path: './lighthouse-report'
