name: Lighthouse CI
on: 
  push:
  workflow_dispatch:  
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: my-lhci
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://www.mini.de/de-de/sl/fahrzeugsuche#/results
          budgetPath: ../budget.json # test performance budgets
          # uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: check dir contents
        id: dir-content
        shell: bash
        run: |
          cp -r ${{ steps.my-lhci.outputs.resultsPath }} ./lhci/
          ls ./lhci/

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          # The name the artifact will have in the Actions "Artifacts" section
          name: lighthouse-reports
          # Must point to the same path defined in `output_path`
          path: /home/runner/work/startupfocus/startupfocus/.lighthouseci
